<a href="https://colab.research.google.com/github/programmer-plus-cn/cola-test/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("python")

python


In [3]:
import numpy as np
a = np.array([1,2,3,4])
a
print(a.shape)

(4,)


In [15]:
import numpy as np
# a = np.arange(10001)
a = np.random.random((2,3))
print(a)
print(a.sum())
print(a.min())
print(a.max())

[[0.96314626 0.00290282 0.29898917]
 [0.9603305  0.96379412 0.07843899]]
3.267601856128538
0.0029028239593102967
0.9637941170905568


In [17]:
import numpy as np
a = np.arange(10) ** 3
print(a)
print(a[2])
print(a[2:4])
print(a[2:])

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27]
[  8  27  64 125 216 343 512 729]
